import { TeamMember } from "@/types/team";

export const TEAM_MEMBERS: TeamMember[] = [
    {
        id: "1",
        name: "Austin Kocher",
        role: "Public Impact Strategist",
        department: "Management",
        imageUrl: "/assets/team/austin.jpg",
        bio: "Austin leads our public impact strategies and outreach initiatives.",
        isActive: true,
        socialLinks: {
            linkedin: "https://www.linkedin.com/in/austinkocher/",
        },
    },
    {
        id: "2",
        name: "Adam Sawyer",
        role: "Data Analyst",
        department: "Research",
        imageUrl: "/assets/team/adam1.jpg",
        bio: "Adam specializes in data analysis and research methodologies.",
        isActive: true,
        socialLinks: {
            twitter: "https://twitter.com",
            linkedin: "https://www.linkedin.com/in/adam-sawyer-tan/",
        },
    },
    {
        id: "3",
        name: "Riwaj Chalise",
        role: "Team Lead",
        department: "Software Development",
        imageUrl: "/assets/team/riwaj.jpeg",
        bio: "Riwaj leads our development team and oversees technical projects.",
        isActive: true,
        socialLinks: {
            linkedin: "https://www.linkedin.com/in/riwajchalise/",
        },
    },
    {
        id: "4",
        name: "Michael Ale",
        role: "Data Scientist",
        department: "Research",
        imageUrl: "/assets/team/michael.png",
        bio: "Michael focuses on data science and statistical analysis.",
        isActive: true,
        socialLinks: {
            linkedin: "https://www.linkedin.com/in/michael-ale-315bbb1bb/",
        },
    },
    // {
    //     id: "5",
    //     name: "Sunita Kunwar",
    //     role: "Data Analyst",
    //     department: "Research",
    //     imageUrl: "/assets/team/sunita.jpeg",
    //     bio: "Sunita conducts detailed data analysis and research support.",
    //     isActive: true,
    //     socialLinks: {
    //         linkedin: "https://www.linkedin.com/in/sunita-kunwar-919b67151/",
    //     },
    // },
    {
        id: "6",
        name: "Bishal Timsina",
        role: "Web Developer",
        department: "Software Development",
        imageUrl: "/assets/team/bishal.jpeg",
        bio: "Bishal develops and maintains our web applications.",
        isActive: true,
        socialLinks: {
            linkedin: "https://www.linkedin.com/in/bishal-timsina-aa381b263/",
        },
    },
    {
        id: "7",
        name: "Sandesh Nilas Khatiwada",
        role: "Web Developer",
        department: "Software Development",
        imageUrl: "/assets/team/sandesh.jpeg",
        bio: "Sandesh is a full-stack developer with expertise in modern web technologies.",
        isActive: true,
        socialLinks: {
            linkedin: "https://www.linkedin.com/in/sandesh-nilas-khatiwada-9b503b280/",
        },
    },
    // {
    //     id: "8",
    //     name: "Srijana Shrestha",
    //     role: "Content Strategist",
    //     department: "Marketing",
    //     imageUrl: "/assets/team/srijana.jpeg",
    //     bio: "Srijana develops and manages our content strategy.",
    //     isActive: true,
    //     socialLinks: {},
    // },
    {
        id: "9",
        name: "Pranisha Acharya",
        role: "People and Projects Coordinator",
        department: "Management",
        imageUrl: "/assets/team/pranisha.jpeg",
        bio: "Pranisha coordinates our team activities and project management.",
        isActive: true,
        socialLinks: {},
    },
];